#NOTE: z values are depth x is width y is height
logLevel: ""
lastScanPath: ""
autoConnect: true
autoReload : true


vision:
  upperLimit: 0
  lowerLimit: 30
  originY: 0.75 #defining the origin in the cvFrame :the position of intersection of back plane with ground plane in cvFrame in percent
  #check the yellow laser line to calibrate the yellow laser line should touch the bottom plane
  lineExtractionParams:
    gaussBlurKernel:
      - 15
      - 15
    threshold: 22
    erosion: 2
    dilation: 5
    outThreshold: 250
    maxDist: 40

camera:
  position: 
    x: 0 #precise by construction
    y: 5.57
    z: 30.9

  frameWidth : 26.6   #in cm. the width of what the camera sees ie place a measure tool at the back-plane and see how many cm the camera sees.
  imWidth : 1280
  imHeight : 960
  framesToFlush : 25
  flipX: false
  flipY: false

laser:
  position: 
    x: 14.0 #precise by construction
    y: 6.4 #not needed/used for calculations
    z: 28.8 #precise by construction
  pointPosition:
    x: 14.0
    y: 0.0
    z: 0.0
  rotation:
    x: 0
    y: 0
    z: 0
  swipeRange:
    min: 18.0
    max: 52.0
  
  #as the actual position in the frame differs a little from calculated laserline 
  #we stop a little befor as we might catch the real non reflected laser line which creates noise
  analyzingOffset: 90
  togglingDelay: 20 #how much time until laser is actually switched on/off

turntable:
  position: 
    x: 0 #not used by calculations
    y: 0 #not used by calculations
    z: 7.5 #precise by construction
  rotation:
    x: 0
    y: 0
    z: 0
  microSteps: 16


